site_name: RenderCV
site_description: A Python application that creates a CV in PDF from a YAML/JSON input file.
site_url: https://sinaatalay.github.io/rendercv/
repo_name: sinaatalay/rendercv
repo_url: https://github.com/sinaatalay/rendercv
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy

nav:
  - Quick Start: index.md
  - Contact: contact.md
  - Code Reference:
      - __main__.py: reference/__main__.md
      - data_model.py: reference/data_model.md
      - tinytex.py: reference/tinytex.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - rendercv
          options:
            members_order: source
            show_bases: true
            docstring_section_style: list
            merge_init_into_class: true
            show_docstring_attributes: true
            docstring_style: google