site_name: My Docs
theme:
  name: material

nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md
  - License: license.md
  - Code Reference:
    - __main__.py: code/main.md
    - data_model.py: code/data_model.md
    - tinytex.py: code/tinytex.md

plugins:
  - search
  - mkdocstrings